### ISSUE TITLE
Testing the model

### ISSUE THREAD

**Issue by Zumbalamambo** [Shahnawax/HAR-CNN-Keras#1]
How do I test the code in realtime video?

**Comment by Shahnawax** [comment]
Dear Zumbalamambo
I am not sure if I understand your question. What I understood is that you want to run the code for your own data. Is it so? If yes, then just make sure the dimensions of the input and output are same and it must work for your input and output.
The data we are using has a sampling rate of 20 samples/second and we are segmenting the data into frames of 90 samples each with a 50% overlap. Which means each segment will be 4.5 seconds long with an overlap of 2.25 seconds.

Let me know if you mean something else.

**Comment by Shahnawax** [comment]
As there is not activity in this thread anymore so I am closing it.
