### ISSUE TITLE
invalid network

### ISSUE THREAD

**Issue by xunyiljg** [Shahnawax/HAR-CNN-Keras#3]
When I analyze my keras model, it is 'invalid network', it is because the version of keras or what?

**Comment by Shahnawax** [comment]
Can you be a little bit more specific? 
Are you asking if you create a network you are not able to analyze it? Or you are trying to analyze the network provided in this repository?

**Comment by xunyiljg** [comment]
The problem has been solved. The problem is that I used the keras module in tensorflow. Other reasons for errors are that some neural network layers are not yet supported, such as bilstm, upsampling.

**Comment by Shahnawax** [comment]
OK. I am closing the issue now...
